### ISSUE TITLE
Passing data from CJR to the workers

### ISSUE THREAD

**Issue by binygal** [rogeliog/create-jest-runner#3]
This is a feature suggestions. I would love to have an agreement about the design, than I will implement it. 

**The problem** - I have a use case that I need to do some expensive operation in the runner. I can do it once, but I don't have a way to pass the data to the workers. Solving it by repeating the operation inside each worker will reduce the performance that the jest runner approach will be useless.

**Suggested solution** - Naive approach. Let CJR (create jest runner) pass an optional data object. Each worker can pass the data object to the worker as an argument inside the OnStart function.

**Comment by slightlytyler** [comment]
I've talked with @rogeliog about this and we think your use case lies outside of `create-jest-runner`. `create-jest-runner` serves to abstract away the logic of spinning up runners to parallelize with. The flowtype runner doesn't require parallelization and would actually incur more overhead by using it. We think the best course of action is to make a custom built runner and remove the dep on `create-jest-runner`

**Comment by binygal** [comment]
👍 I agree, I had lots of doubts with my suggestion.
